# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame_controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frame_controller.proto',
  package='frame_controller',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x66rame_controller.proto\x12\x10\x66rame_controller\"\x10\n\x0eStopAllRequest\"\"\n\x10StopMotorRequest\x12\x0e\n\x06motors\x18\x01 \x01(\x07\"N\n\x12SetVelocityRequest\x12\x0e\n\x06motors\x18\x01 \x01(\x07\x12\x12\n\nduty_cycle\x18\x02 \x01(\x02\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x02\"\x08\n\x06Status*7\n\rMotorBitshift\x12\x12\n\x0e\x43ONT1_BITSHIFT\x10\x00\x12\x12\n\x0e\x43ONT2_BITSHIFT\x10\x03*\xa1\x01\n\tMotorEnum\x12\x0c\n\x08NO_MOTOR\x10\x00\x12\x10\n\x0c\x43ONT1_MOTOR1\x10\x01\x12\x10\n\x0c\x43ONT1_MOTOR2\x10\x02\x12\x0e\n\nCONT1_BOTH\x10\x04\x12\x0e\n\nCONT1_MASK\x10\x07\x12\x10\n\x0c\x43ONT2_MOTOR1\x10\x08\x12\x10\n\x0c\x43ONT2_MOTOR2\x10\x10\x12\x0e\n\nCONT2_BOTH\x10 \x12\x0e\n\nCONT2_MASK\x10?2\xf8\x01\n\x0f\x46rameController\x12G\n\x07StopAll\x12 .frame_controller.StopAllRequest\x1a\x18.frame_controller.Status\"\x00\x12K\n\tStopMotor\x12\".frame_controller.StopMotorRequest\x1a\x18.frame_controller.Status\"\x00\x12O\n\x0bSetVelocity\x12$.frame_controller.SetVelocityRequest\x1a\x18.frame_controller.Status\"\x00\x62\x06proto3')
)

_MOTORBITSHIFT = _descriptor.EnumDescriptor(
  name='MotorBitshift',
  full_name='frame_controller.MotorBitshift',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONT1_BITSHIFT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_BITSHIFT', index=1, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=188,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_MOTORBITSHIFT)

MotorBitshift = enum_type_wrapper.EnumTypeWrapper(_MOTORBITSHIFT)
_MOTORENUM = _descriptor.EnumDescriptor(
  name='MotorEnum',
  full_name='frame_controller.MotorEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_MOTOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT1_MOTOR1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT1_MOTOR2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT1_BOTH', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT1_MASK', index=4, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_MOTOR1', index=5, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_MOTOR2', index=6, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_BOTH', index=7, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_MASK', index=8, number=63,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=246,
  serialized_end=407,
)
_sym_db.RegisterEnumDescriptor(_MOTORENUM)

MotorEnum = enum_type_wrapper.EnumTypeWrapper(_MOTORENUM)
CONT1_BITSHIFT = 0
CONT2_BITSHIFT = 3
NO_MOTOR = 0
CONT1_MOTOR1 = 1
CONT1_MOTOR2 = 2
CONT1_BOTH = 4
CONT1_MASK = 7
CONT2_MOTOR1 = 8
CONT2_MOTOR2 = 16
CONT2_BOTH = 32
CONT2_MASK = 63



_STOPALLREQUEST = _descriptor.Descriptor(
  name='StopAllRequest',
  full_name='frame_controller.StopAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=60,
)


_STOPMOTORREQUEST = _descriptor.Descriptor(
  name='StopMotorRequest',
  full_name='frame_controller.StopMotorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motors', full_name='frame_controller.StopMotorRequest.motors', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=96,
)


_SETVELOCITYREQUEST = _descriptor.Descriptor(
  name='SetVelocityRequest',
  full_name='frame_controller.SetVelocityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motors', full_name='frame_controller.SetVelocityRequest.motors', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duty_cycle', full_name='frame_controller.SetVelocityRequest.duty_cycle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='frame_controller.SetVelocityRequest.duration_sec', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=176,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='frame_controller.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['StopAllRequest'] = _STOPALLREQUEST
DESCRIPTOR.message_types_by_name['StopMotorRequest'] = _STOPMOTORREQUEST
DESCRIPTOR.message_types_by_name['SetVelocityRequest'] = _SETVELOCITYREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['MotorBitshift'] = _MOTORBITSHIFT
DESCRIPTOR.enum_types_by_name['MotorEnum'] = _MOTORENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopAllRequest = _reflection.GeneratedProtocolMessageType('StopAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPALLREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.StopAllRequest)
  ))
_sym_db.RegisterMessage(StopAllRequest)

StopMotorRequest = _reflection.GeneratedProtocolMessageType('StopMotorRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPMOTORREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.StopMotorRequest)
  ))
_sym_db.RegisterMessage(StopMotorRequest)

SetVelocityRequest = _reflection.GeneratedProtocolMessageType('SetVelocityRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETVELOCITYREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.SetVelocityRequest)
  ))
_sym_db.RegisterMessage(SetVelocityRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.Status)
  ))
_sym_db.RegisterMessage(Status)



_FRAMECONTROLLER = _descriptor.ServiceDescriptor(
  name='FrameController',
  full_name='frame_controller.FrameController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=410,
  serialized_end=658,
  methods=[
  _descriptor.MethodDescriptor(
    name='StopAll',
    full_name='frame_controller.FrameController.StopAll',
    index=0,
    containing_service=None,
    input_type=_STOPALLREQUEST,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopMotor',
    full_name='frame_controller.FrameController.StopMotor',
    index=1,
    containing_service=None,
    input_type=_STOPMOTORREQUEST,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetVelocity',
    full_name='frame_controller.FrameController.SetVelocity',
    index=2,
    containing_service=None,
    input_type=_SETVELOCITYREQUEST,
    output_type=_STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMECONTROLLER)

DESCRIPTOR.services_by_name['FrameController'] = _FRAMECONTROLLER

# @@protoc_insertion_point(module_scope)
