# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame_controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frame_controller.proto',
  package='frame_controller',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x66rame_controller.proto\x12\x10\x66rame_controller\"\x10\n\x0eStopAllRequest\"0\n\x10StopMotorRequest\x12\x0e\n\x06motors\x18\x01 \x01(\x07\x12\x0c\n\x04\x61xes\x18\x02 \x01(\x07\"\\\n\x12SetVelocityRequest\x12\x0e\n\x06motors\x18\x01 \x01(\x07\x12\x0c\n\x04\x61xes\x18\x02 \x01(\x07\x12\x12\n\nduty_cycle\x18\x03 \x01(\x02\x12\x14\n\x0c\x64uration_sec\x18\x04 \x01(\x02\"\x08\n\x06Status*6\n\tMotorAxis\x12\x0b\n\x07NO_AXES\x10\x00\x12\x0e\n\nAXIS_PITCH\x10\x01\x12\x0c\n\x08\x41XIS_YAW\x10\x02*J\n\tMotorEnum\x12\x0c\n\x08NO_MOTOR\x10\x00\x12\x0f\n\x0b\x43ONT_MOTOR1\x10\x01\x12\x0f\n\x0b\x43ONT_MOTOR2\x10\x02\x12\r\n\tCONT_BOTH\x10\x03\x32\xf8\x01\n\x0f\x46rameController\x12G\n\x07StopAll\x12 .frame_controller.StopAllRequest\x1a\x18.frame_controller.Status\"\x00\x12K\n\tStopMotor\x12\".frame_controller.StopMotorRequest\x1a\x18.frame_controller.Status\"\x00\x12O\n\x0bSetVelocity\x12$.frame_controller.SetVelocityRequest\x1a\x18.frame_controller.Status\"\x00\x62\x06proto3')
)

_MOTORAXIS = _descriptor.EnumDescriptor(
  name='MotorAxis',
  full_name='frame_controller.MotorAxis',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_AXES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AXIS_PITCH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AXIS_YAW', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=216,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_MOTORAXIS)

MotorAxis = enum_type_wrapper.EnumTypeWrapper(_MOTORAXIS)
_MOTORENUM = _descriptor.EnumDescriptor(
  name='MotorEnum',
  full_name='frame_controller.MotorEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_MOTOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT_MOTOR1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT_MOTOR2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT_BOTH', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=272,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_MOTORENUM)

MotorEnum = enum_type_wrapper.EnumTypeWrapper(_MOTORENUM)
NO_AXES = 0
AXIS_PITCH = 1
AXIS_YAW = 2
NO_MOTOR = 0
CONT_MOTOR1 = 1
CONT_MOTOR2 = 2
CONT_BOTH = 3



_STOPALLREQUEST = _descriptor.Descriptor(
  name='StopAllRequest',
  full_name='frame_controller.StopAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=60,
)


_STOPMOTORREQUEST = _descriptor.Descriptor(
  name='StopMotorRequest',
  full_name='frame_controller.StopMotorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motors', full_name='frame_controller.StopMotorRequest.motors', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axes', full_name='frame_controller.StopMotorRequest.axes', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=110,
)


_SETVELOCITYREQUEST = _descriptor.Descriptor(
  name='SetVelocityRequest',
  full_name='frame_controller.SetVelocityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motors', full_name='frame_controller.SetVelocityRequest.motors', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axes', full_name='frame_controller.SetVelocityRequest.axes', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duty_cycle', full_name='frame_controller.SetVelocityRequest.duty_cycle', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='frame_controller.SetVelocityRequest.duration_sec', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=204,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='frame_controller.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['StopAllRequest'] = _STOPALLREQUEST
DESCRIPTOR.message_types_by_name['StopMotorRequest'] = _STOPMOTORREQUEST
DESCRIPTOR.message_types_by_name['SetVelocityRequest'] = _SETVELOCITYREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['MotorAxis'] = _MOTORAXIS
DESCRIPTOR.enum_types_by_name['MotorEnum'] = _MOTORENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopAllRequest = _reflection.GeneratedProtocolMessageType('StopAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPALLREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.StopAllRequest)
  ))
_sym_db.RegisterMessage(StopAllRequest)

StopMotorRequest = _reflection.GeneratedProtocolMessageType('StopMotorRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPMOTORREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.StopMotorRequest)
  ))
_sym_db.RegisterMessage(StopMotorRequest)

SetVelocityRequest = _reflection.GeneratedProtocolMessageType('SetVelocityRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETVELOCITYREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.SetVelocityRequest)
  ))
_sym_db.RegisterMessage(SetVelocityRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.Status)
  ))
_sym_db.RegisterMessage(Status)



_FRAMECONTROLLER = _descriptor.ServiceDescriptor(
  name='FrameController',
  full_name='frame_controller.FrameController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=349,
  serialized_end=597,
  methods=[
  _descriptor.MethodDescriptor(
    name='StopAll',
    full_name='frame_controller.FrameController.StopAll',
    index=0,
    containing_service=None,
    input_type=_STOPALLREQUEST,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopMotor',
    full_name='frame_controller.FrameController.StopMotor',
    index=1,
    containing_service=None,
    input_type=_STOPMOTORREQUEST,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetVelocity',
    full_name='frame_controller.FrameController.SetVelocity',
    index=2,
    containing_service=None,
    input_type=_SETVELOCITYREQUEST,
    output_type=_STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMECONTROLLER)

DESCRIPTOR.services_by_name['FrameController'] = _FRAMECONTROLLER

# @@protoc_insertion_point(module_scope)
