# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame_controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frame_controller.proto',
  package='frame_controller',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x66rame_controller.proto\x12\x10\x66rame_controller\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x10\n\x0eStopAllRequest\"\"\n\x10StopMotorRequest\x12\x0e\n\x06motors\x18\x01 \x01(\x07\"O\n\x12SetVelocityRequest\x12\x0e\n\x06motors\x18\x01 \x01(\x07\x12\x13\n\x0b\x64uty_cycles\x18\x02 \x01(\x07\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x02\"\x08\n\x06Status*`\n\tMotorEnum\x12\x0b\n\x07NOMOTOR\x10\x00\x12\x10\n\x0c\x43ONT1_MOTOR1\x10\x01\x12\x10\n\x0c\x43ONT1_MOTOR2\x10\x02\x12\x10\n\x0c\x43ONT2_MOTOR1\x10\x04\x12\x10\n\x0c\x43ONT2_MOTOR2\x10\x08\x32\xfd\x01\n\x0f\x46rameController\x12G\n\x07StopAll\x12 .frame_controller.StopAllRequest\x1a\x18.frame_controller.Status\"\x00\x12K\n\tStopMotor\x12\".frame_controller.StopMotorRequest\x1a\x18.frame_controller.Status\"\x00\x12T\n\x10SetMotorVelocity\x12$.frame_controller.SetVelocityRequest\x1a\x18.frame_controller.Status\"\x00\x62\x06proto3')
)

_MOTORENUM = _descriptor.EnumDescriptor(
  name='MotorEnum',
  full_name='frame_controller.MotorEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOMOTOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT1_MOTOR1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT1_MOTOR2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_MOTOR1', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONT2_MOTOR2', index=4, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=250,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_MOTORENUM)

MotorEnum = enum_type_wrapper.EnumTypeWrapper(_MOTORENUM)
NOMOTOR = 0
CONT1_MOTOR1 = 1
CONT1_MOTOR2 = 2
CONT2_MOTOR1 = 4
CONT2_MOTOR2 = 8



_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='frame_controller.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='frame_controller.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=72,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='frame_controller.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='frame_controller.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=103,
)


_STOPALLREQUEST = _descriptor.Descriptor(
  name='StopAllRequest',
  full_name='frame_controller.StopAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=121,
)


_STOPMOTORREQUEST = _descriptor.Descriptor(
  name='StopMotorRequest',
  full_name='frame_controller.StopMotorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motors', full_name='frame_controller.StopMotorRequest.motors', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=157,
)


_SETVELOCITYREQUEST = _descriptor.Descriptor(
  name='SetVelocityRequest',
  full_name='frame_controller.SetVelocityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motors', full_name='frame_controller.SetVelocityRequest.motors', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duty_cycles', full_name='frame_controller.SetVelocityRequest.duty_cycles', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration_sec', full_name='frame_controller.SetVelocityRequest.duration_sec', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=238,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='frame_controller.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=248,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['StopAllRequest'] = _STOPALLREQUEST
DESCRIPTOR.message_types_by_name['StopMotorRequest'] = _STOPMOTORREQUEST
DESCRIPTOR.message_types_by_name['SetVelocityRequest'] = _SETVELOCITYREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['MotorEnum'] = _MOTORENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

StopAllRequest = _reflection.GeneratedProtocolMessageType('StopAllRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPALLREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.StopAllRequest)
  ))
_sym_db.RegisterMessage(StopAllRequest)

StopMotorRequest = _reflection.GeneratedProtocolMessageType('StopMotorRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPMOTORREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.StopMotorRequest)
  ))
_sym_db.RegisterMessage(StopMotorRequest)

SetVelocityRequest = _reflection.GeneratedProtocolMessageType('SetVelocityRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETVELOCITYREQUEST,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.SetVelocityRequest)
  ))
_sym_db.RegisterMessage(SetVelocityRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'frame_controller_pb2'
  # @@protoc_insertion_point(class_scope:frame_controller.Status)
  ))
_sym_db.RegisterMessage(Status)



_FRAMECONTROLLER = _descriptor.ServiceDescriptor(
  name='FrameController',
  full_name='frame_controller.FrameController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=349,
  serialized_end=602,
  methods=[
  _descriptor.MethodDescriptor(
    name='StopAll',
    full_name='frame_controller.FrameController.StopAll',
    index=0,
    containing_service=None,
    input_type=_STOPALLREQUEST,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopMotor',
    full_name='frame_controller.FrameController.StopMotor',
    index=1,
    containing_service=None,
    input_type=_STOPMOTORREQUEST,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetMotorVelocity',
    full_name='frame_controller.FrameController.SetMotorVelocity',
    index=2,
    containing_service=None,
    input_type=_SETVELOCITYREQUEST,
    output_type=_STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMECONTROLLER)

DESCRIPTOR.services_by_name['FrameController'] = _FRAMECONTROLLER

# @@protoc_insertion_point(module_scope)
