# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import frame_controller_pb2 as frame__controller__pb2


class FrameControllerStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StopAll = channel.unary_unary(
        '/frame_controller.FrameController/StopAll',
        request_serializer=frame__controller__pb2.StopAllRequest.SerializeToString,
        response_deserializer=frame__controller__pb2.Status.FromString,
        )
    self.StopMotor = channel.unary_unary(
        '/frame_controller.FrameController/StopMotor',
        request_serializer=frame__controller__pb2.StopMotorRequest.SerializeToString,
        response_deserializer=frame__controller__pb2.Status.FromString,
        )
    self.SetMotorVelocity = channel.unary_unary(
        '/frame_controller.FrameController/SetMotorVelocity',
        request_serializer=frame__controller__pb2.SetVelocityRequest.SerializeToString,
        response_deserializer=frame__controller__pb2.Status.FromString,
        )


class FrameControllerServicer(object):
  """The greeting service definition.
  """

  def StopAll(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopMotor(self, request, context):
    """Stop on
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMotorVelocity(self, request, context):
    """
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FrameControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StopAll': grpc.unary_unary_rpc_method_handler(
          servicer.StopAll,
          request_deserializer=frame__controller__pb2.StopAllRequest.FromString,
          response_serializer=frame__controller__pb2.Status.SerializeToString,
      ),
      'StopMotor': grpc.unary_unary_rpc_method_handler(
          servicer.StopMotor,
          request_deserializer=frame__controller__pb2.StopMotorRequest.FromString,
          response_serializer=frame__controller__pb2.Status.SerializeToString,
      ),
      'SetMotorVelocity': grpc.unary_unary_rpc_method_handler(
          servicer.SetMotorVelocity,
          request_deserializer=frame__controller__pb2.SetVelocityRequest.FromString,
          response_serializer=frame__controller__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'frame_controller.FrameController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
