#!/usr/bin/env python

# Copyright 2018 UW-APL
# See LICENSE

"""The Python implementation of the GRPC frame.Controller server."""

from frame_controller import server

# Configurathe logger used within the frame_controller library
import logging
logger = logging.getLogger('frame_controller')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())

if __name__ == '__main__':
    server.serve()
