#!/usr/bin/env python
# Copyright 2018 UW-APL
# See LICENSE

from yostlabs.client import ImuClient
import argparse
import pika
import logging

def run():
    parser = argparse.ArgumentParser(description='IMU test client.')
    parser.add_argument('name', help='Name for IMU')


    parser.add_argument('--mq-user', default='guest', dest='mquser', help="RabbitMQ Username")
    parser.add_argument('--mq-passwd', default='guest', dest='mqpwd', help="RabbitMQ Username")


    args = parser.parse_args()

    client = ImuClient(args.name,
                       credentials=pika.PlainCredentials(args.mquser, args.mqpwd) )

    # Configure the logger built into the imu server
    client.logger.setLevel(logging.INFO)
    client.logger.addHandler(logging.StreamHandler())

    client.run()

if __name__ == '__main__':

    run()
