#!/usr/bin/env python
# Copyright 2018 UW-APL
# See LICENSE

from yostlabs.client import ImuClient
import argparse
import pika

import logging

def run():
    parser = argparse.ArgumentParser(description='IMU test client.')
    parser.add_argument('name', help='Name for IMU')

    args = parser.parse_args()

    client = ImuClient(args.name)

    # Configure the logger built into the imu server
    client.logger.setLevel(logging.INFO)
    client.logger.addHandler(logging.StreamHandler())

    client.run()

if __name__ == '__main__':

    run()
