#!/usr/bin/env python
# Copyright 2018 UW-APL
# See LICENSE

# Launch an IMU server

from yostlabs.server import ImuServer
import argparse

import logging
import pika

def run():

    # Parse command line args
    parser = argparse.ArgumentParser(description='IMU server.')
    parser.add_argument('--fake-hardware', dest='fakehw', action='store_true',
                        help='Use fake PWM hardware')
    parser.add_argument('name', help='Name of the IMU')
    parser.add_argument('port', help='Serial port (ignored for --fake-hardware)')

    parser.add_argument('--mq-user', default='guest', dest='mquser', help="RabbitMQ Username")
    parser.add_argument('--mq-passwd', default='guest', dest='mqpwd', help="RabbitMQ Username")


    args = parser.parse_args()

    server = ImuServer(args.name, fakehw=args.fakehw, port=args.port,
                        credentials=pika.PlainCredentials(args.mquser, args.mqpwd) )

    # Configure the IMU server's logger
    server.logger.setLevel(logging.INFO)
    server.logger.addHandler(logging.StreamHandler())

    try:
        server.run()
    except KeyboardInterrupt:
        server.close()

if __name__ == '__main__':

    run()
